//
// Created by Lucas Angelozzi on 4/10/2023.
//

#ifndef HUFF_MY_FILE_HELPERS_H
#define HUFF_MY_FILE_HELPERS_H

#include <unordered_map>
#include <vector>

/**
 * Print the codewords generated by the Huffman algorithm to stdout.
 * @param codewords the map of characters with their corresponding codewords
 */
void printCodeWords(std::unordered_map<char, std::vector<int>*>* codewords);

#endif //HUFF_MY_FILE_HELPERS_H
